spring:
    rabbitmq:
        addresses: localhost
        username: guest
        password: guest

server:
    port: 9001

rabbitmq:
    queues:
        default-queue: consumer-service1.default.queue
        fanout-queue: consumer-service1.fanout.queue
        direct-queue: consumer-service1.direct.queue
    routing-keys:
        direct-queue: 1
    exchanges:
        producer-service-fanout-exchange: producer-service.fanout.exchange
        producer-service-direct-exchange: producer-service.direct.exchange
