spring:
    rabbitmq:
        addresses: localhost
        username: guest
        password: guest
        
springdoc:
    show-actuator: true

server:
    port: 9000

service:
    rest-api: '/api'

rabbitmq:
    routing-keys:
        default-queue: consumer-service1.default.queue
    exchanges:
        producer-service-fanout-exchange: producer-service.fanout.exchange
        producer-service-direct-exchange: producer-service.direct.exchange